### ISSUE TITLE
Run examples to verify correct behavior

### ISSUE THREAD

**Issue by eventualbuddha** [fdecampredon/es6-destructuring#1]
The tests currently only parse and print the example files to verify that the transformation does not fail, but it does not verify correctness by actually running the code. If you'd like to follow the same pattern used by many of the other es6-\* projects you can use [example-runner](https://github.com/square/example-runner) which I wrote specifically for this purpose.

**Comment by fdecampredon** [comment]
I used example-runner in the same way that is used in es6-arrow-function, let me  know if you feel there is place for more tests.
