### ISSUE TITLE
Handle empty object and array destructures

### ISSUE THREAD

**Issue by eventualbuddha** [fdecampredon/es6-destructuring#2]
Adding these to the test files caused unexpected output:

``` js
var {} = z;
var [] = z;
```

Turns into:

``` js
var undefined;
var undefined;
```

These should turn into something like this:

``` js
var var$0 = z;
var var$1 = z;
```

**Comment by fdecampredon** [comment]
@eventualbuddha it seems ok for me I let you check that yourself and close the issue

**Comment by eventualbuddha** [comment]
This appears to be fixed.
