### ISSUE TITLE
Array destructuring should use @@iterator

### ISSUE THREAD

**Issue by eventualbuddha** [fdecampredon/es6-destructuring#3]
Currently this:

``` js
var [x] = arr;
var [...y] = arr;
```

Turns into this:

``` js
var x = arr[0];
var y = arr.slice(0);
```

But per the [spec](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-runtime-semantics-destructuringassignmentevaluation) we need to get the iterator of the right-hand side and use it to get the values to be assigned to the left-hand side bindings (e.g. `x` and `y`).

esnext does not handle this completely correctly yet in other areas (such as `for-of`), but I'm working on it. You can use [ast-util](https://github.com/square/ast-util)'s iterator-related methods to help you build this.

**Comment by eventualbuddha** [comment]
Since this has the potential of blowing up the source code a fair amount more than expected, it might make sense for this to be something we can disable with an option. That is, optionally fall back to assuming that indexing and slicing are acceptable.

**Comment by fdecampredon** [comment]
@eventualbuddha I'll let you check the result and close the issue but everything seems alright for me, actually the transform depends on this pr https://github.com/square/ast-util/pull/1.

**Comment by eventualbuddha** [comment]
I had to install some missing dependencies (#5). Even after that, the tests don't seem to pass:

```
$ npm test

> es6-destructuring@0.1.0 test /Users/donovan/Development/public/es6-destructuring
> node test/runner.js

✘ arrayElission

AssertionError: ensure that array elision works
    at evalmachine.<anonymous>:80:8
    at /Users/donovan/Development/public/es6-destructuring/node_modules/example-runner/lib/index.js:49:10
    at fs.js:271:14
    at Object.oncomplete (fs.js:107:15)
✓ complexValueExpression
✓ emptyPattern
✓ functionDestructuring
✓ mixedPattern
✘ restParameter

AssertionError: ensure that destructuring with variable elision and rest works
    at evalmachine.<anonymous>:109:8
    at /Users/donovan/Development/public/es6-destructuring/node_modules/example-runner/lib/index.js:49:10
    at fs.js:271:14
    at Object.oncomplete (fs.js:107:15)
✓ simpleValue
✓ variableRenaming

8 total, 6 passed, 2 failed.
```

Is this expected?

**Comment by fdecampredon** [comment]
Yeah actually the transform works only if you use my version of recast due to https://github.com/benjamn/recast/issues/95, I for the moment added the dependencies over my repository, until the issue is fixed

**Comment by eventualbuddha** [comment]
This appears to be fixed.
